name: contac_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  keyboard_avoider: ^0.2.0
  lottie: ^3.2.0
  cloud_firestore: ^5.6.4
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/logoApp.png
  android: true
  ios: true
  fullscreen: true
